// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsiZqslkjILEWQ4KGSc2QLzOYlJCtBdMU',
    appId: '1:5350672937:web:2024b5fd63414205b96a38',
    messagingSenderId: '5350672937',
    projectId: 'tutorials-world-new',
    authDomain: 'tutorials-world-new.firebaseapp.com',
    storageBucket: 'tutorials-world-new.appspot.com',
    measurementId: 'G-CTL7ZP85VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_4oUzb7oV-X0k8ITMNoNRbQ4N28rbVY',
    appId: '1:5350672937:android:0b4788f25bcaaaccb96a38',
    messagingSenderId: '5350672937',
    projectId: 'tutorials-world-new',
    storageBucket: 'tutorials-world-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3raSvGMsyZGTjKMTK5B5ZuV5EnfqnlG0',
    appId: '1:5350672937:ios:cc60ba1a9fb875d0b96a38',
    messagingSenderId: '5350672937',
    projectId: 'tutorials-world-new',
    storageBucket: 'tutorials-world-new.appspot.com',
    iosBundleId: 'com.mohammadareebkashaf.tutorialsWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3raSvGMsyZGTjKMTK5B5ZuV5EnfqnlG0',
    appId: '1:5350672937:ios:cc60ba1a9fb875d0b96a38',
    messagingSenderId: '5350672937',
    projectId: 'tutorials-world-new',
    storageBucket: 'tutorials-world-new.appspot.com',
    iosBundleId: 'com.mohammadareebkashaf.tutorialsWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsiZqslkjILEWQ4KGSc2QLzOYlJCtBdMU',
    appId: '1:5350672937:web:5ab671d22c5557d7b96a38',
    messagingSenderId: '5350672937',
    projectId: 'tutorials-world-new',
    authDomain: 'tutorials-world-new.firebaseapp.com',
    storageBucket: 'tutorials-world-new.appspot.com',
    measurementId: 'G-V8EY598CRH',
  );
}
